# Generated by Django 4.2.1 on 2023-06-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='page_name',
            field=models.CharField(choices=[('about', 'About'), ('contact', 'Contact'), ('home-slider1', 'Home Slider 1'), ('home-slider2', 'Home Slider 2'), ('home-slider3', 'Home Slider 3')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
