# Generated by Django 4.2.2 on 2023-06-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_summary',
            field=models.CharField(default='Default Value', max_length=200),
        ),
    ]
