# Generated by Django 3.1.7 on 2023-06-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='content',
            name='page_name',
            field=models.CharField(choices=[('about', 'About'), ('contact', 'Contact'), ('home-slider1', 'Home Slider 1'), ('home-slider2', 'Home Slider 2'), ('home-slider3', 'Home Slider 3'), ('home-slider4', 'Home Slider 4')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
