# Generated by Django 4.2.1 on 2023-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_contact_alter_content_id_alter_donation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(),
        ),
    ]
