# Generated by Django 4.2.1 on 2023-06-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_guestuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='guest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.guestuser'),
        ),
    ]
