# Generated by Django 4.2.1 on 2023-06-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_donation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
