# Generated by Django 3.1.7 on 2023-06-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20230612_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_plan',
            field=models.CharField(default='Default Value', max_length=2000),
        ),
    ]
