# Generated by Django 3.1.7 on 2023-06-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_program_program_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
