# Generated by Django 3.1.7 on 2023-06-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_count', models.IntegerField(default=0)),
                ('total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('highest_donor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
